### ISSUE TITLE
geolonia/japanese-addresses が提供している最新の CSV ファイルに追随していない

### ISSUE THREAD

**Issue by champierre** [yamat47/japanese_address_parser#60]
geolonia/japanese-addresses が提供している最新の CSV ファイルに追随していないようです。
たとえば、

https://github.com/geolonia/japanese-addresses/issues/118

で issue に挙がっていた「福島県東白川郡矢祭町」のローマ字表記が[デモサイト](https://japanese-address-parser-demo.fly.dev/?search=%E7%A6%8F%E5%B3%B6%E7%9C%8C%E6%9D%B1%E7%99%BD%E5%B7%9D%E9%83%A1%E7%9F%A2%E7%A5%AD%E7%94%BA)では、「HIGASHISHIRAKAWA GUN YAMATSURI MACH」(MACH -> MACHI でないといけない)になっています。これは最新の latest.csv では修正済みです。

japanese-addresses で提供する CSV ファイルは、issues に挙がってくる問題を修正したり、ほかにも[国土地理協会が提供する地名変更情報](https://github.com/geolonia/japanese-addresses/pull/132)を取り込んだりと、毎月更新しているので、できれば、更新があったときに japanese_address_parser も更新される仕組みがあると望ましいと思います。

**Comment by yamat47** [comment]
@champierre ありがとうございます！ 追従できてない問題はずっとあったのですよね、いい機会なので自動化の仕組みを考えて観ます！

**Comment by yamat47** [comment]
参考: https://github.com/yamat47/japanese_address_parser/issues/5

**Comment by yamat47** [comment]
前回手動で更新したときの記録：

* issue: https://github.com/yamat47/japanese_address_parser/issues/31
* pull request: https://github.com/yamat47/japanese_address_parser/pull/45

**Comment by yamat47** [comment]
Dependabot のプルリクエストにフックして node_modules を更新する設定：

```yaml
name: Update node_modules
on:
  pull_request:
    branches:
      # /jsの中のnpmパッケージが更新されたプルリクエストに対してのみ実行する。
      - 'dependabot/npm_and_yarn/js/**'

jobs:
  update_node_modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JavaScript
      uses: actions/setup-node@v2
    - name: Update node_modules
      run: cd js && npm install
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: js/node_modules
        default_author: github_actor
        message: '[Automatic] Update node_modules.'
```

**Comment by yamat47** [comment]
Dependabot のプルリクにフックして CSV を更新する設定：

```yaml
name: Update parsed csv
on:
  pull_request:
    branches:
      # /geolonia-japanese-addressesのサブモジュールが更新されたプルリクエストに対してのみ実行する。
      - 'dependabot/submodules/geolonia-japanese-addresses**'

jobs:
  update_parsed_csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Update parsed csv
      run: bundle exec rake japanese_address_parser:parse_csv
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: lib/japanese_address_parser/data
        default_author: github_actor
        message: '[Automatic] Update parsed csv.'
```
